name: CI/CD for DevOps Practice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker-compose up --build -d

      - name: Wait for the web server
        run: sleep 10

      - name: Install dependencies for tests
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest

      - name: Run unit tests
        run: pytest tests/test_index.py
